apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: coffee 
  namespace: citi
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: coffee 
  template: 
    metadata: 
      labels: 
        app: coffee 
    spec: 
      containers: 
      - name: coffee 
        image: nginxdemos/hello:plain-text 
        ports: 
        - containerPort: 80

--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: coffee-svc 
  namespace: citi
spec: 
  ports: 
  - port: 80 
    targetPort: 80 
    protocol: TCP 
    name: http 
  selector: 
    app: coffee 
    
--- 
apiVersion: apps/v1  

kind: Deployment 
metadata: 
  name: tea 
  namespace: citi
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: tea  
  template: 
    metadata: 
      labels: 
        app: tea  
    spec: 
      containers: 
      - name: tea  
        image: nginxdemos/hello:plain-text 
        ports: 
        - containerPort: 80

--- 

apiVersion: v1
kind: Service
metadata:
  name: tea-svc
  namespace: citi
  labels: 
spec: 
  ports: 
  - port: 80 
    targetPort: 80 
    protocol: TCP 
    name: http 
  selector: 
    app: tea